name: Deploy to Azure App Service
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  AZURE_WEBAPP_NAME: pratham-nextjs-demo    # Your actual Azure App Service name
  AZURE_WEBAPP_PACKAGE_PATH: '.'
  NODE_VERSION: '18.x'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        # Remove cache: 'yarn' since you don't have yarn.lock
        
    - name: Install dependencies
      run: |
        npm install -g yarn
        yarn install
        
    - name: Run linting
      run: yarn lint
      
    - name: Build application
      run: yarn build
      env:
        NODE_ENV: production
        MONGODB_URI: ${{ secrets.MONGODB_URI }}
        JWT_SECRET: ${{ secrets.JWT_SECRET }}
        
    - name: Run tests (if available)
      run: |
        if grep -q '"test"' package.json; then
          echo "Running tests..."
          yarn test
        else
          echo "No test script found, skipping tests"
        fi
        
    - name: Deploy to Azure App Service
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
        
    - name: Health check
      run: |
        echo "Waiting for deployment to complete..."
        sleep 30
        curl -f https://pratham-nextjs-demo-hbhsepg2dwenf9bf.centralindia-0.azurewebsites.net/api/health || exit 1
        
    - name: Notify deployment status
      if: always()
      run: |
        if [ ${{ job.status }} == 'success' ]; then
          echo "✅ Deployment successful!"
          echo "🌐 App URL: https://pratham-nextjs-demo-hbhsepg2dwenf9bf.centralindia-0.azurewebsites.net"
        else
          echo "❌ Deployment failed!"
        fi
