name: Deploy to Azure App Service

on:
  push:
    branches: [ main ]

env:
  AZURE_WEBAPP_NAME: pratham-nextjs-demo
  NODE_VERSION: '20.x'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: 'Checkout code'
      uses: actions/checkout@v4

    - name: 'Setup Node.js'
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: 'Install dependencies'
      run: npm ci

    - name: 'Run linting'
      run: npm run lint

    - name: 'Build application'
      run: npm run build

    - name: 'Login to Azure'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        package: '.'

    - name: 'Health check'
      run: |
        echo "✅ Deployment completed!"
        echo "🌐 App URL: https://pratham-nextjs-demo.azurewebsites.net"
        sleep 30
        curl -f https://pratham-nextjs-demo.azurewebsites.net/api/health || echo "⚠️ Health check failed but app may still work"
